"""Failure-mode library: defaults seeded on first use, and the lookup that
tells which modes apply to an item's symbol category and key."""

from __future__ import annotations

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models import FailureMode

# (category, symbol_key, name, title, local effect template, detection hint,
#  default severity, applicable modes or None, replaces_category)
DEFAULT_FAILURE_MODES: list[tuple] = [
    # Generic valves (hand, ball, globe, needle, butterfly, actuated bodies).
    (
        "valve",
        None,
        "fails_open",
        "Fails open / fails to close",
        "{tag} cannot isolate {service}; flow continues downstream",
        ["PT", "FT", "ZS"],
        8,
        None,
        False,
    ),
    (
        "valve",
        None,
        "fails_closed",
        "Fails closed / fails to open",
        "{tag} blocks {service}; no flow downstream",
        ["PT", "FT", "ZS"],
        6,
        None,
        False,
    ),
    (
        "valve",
        None,
        "external_leak",
        "External leak (stem, body, flange)",
        "{service} released to the environment at {tag}",
        ["PT"],
        7,
        None,
        False,
    ),
    (
        "valve",
        None,
        "internal_leak",
        "Internal leak (seat passing)",
        "{service} passes {tag} while closed",
        ["PT", "TT"],
        6,
        None,
        False,
    ),
    (
        "valve",
        None,
        "fails_to_actuate",
        "Fails to actuate on command",
        "{tag} stays in its last position",
        ["ZS"],
        7,
        None,
        False,
    ),
    (
        "valve",
        None,
        "spurious_actuation",
        "Spurious actuation",
        "{tag} changes position without command",
        ["ZS", "PT"],
        8,
        None,
        False,
    ),
    # Check valves replace the generic valve modes.
    (
        "valve",
        "check_valve",
        "reverse_flow",
        "Reverse flow (seat leak)",
        "{service} flows backwards through {tag}",
        ["PT", "FT"],
        7,
        None,
        True,
    ),
    (
        "valve",
        "check_valve",
        "stuck_closed",
        "Stuck closed",
        "{tag} blocks forward {service} flow",
        ["PT", "FT"],
        6,
        None,
        True,
    ),
    (
        "valve",
        "check_valve",
        "chatter",
        "Chatter / flutter",
        "{tag} oscillates, pressure pulsation downstream",
        ["PT"],
        4,
        None,
        True,
    ),
    (
        "valve",
        "check_valve_swing",
        "reverse_flow",
        "Reverse flow (seat leak)",
        "{service} flows backwards through {tag}",
        ["PT", "FT"],
        7,
        None,
        True,
    ),
    (
        "valve",
        "check_valve_swing",
        "stuck_closed",
        "Stuck closed",
        "{tag} blocks forward {service} flow",
        ["PT", "FT"],
        6,
        None,
        True,
    ),
    # Relief devices replace the generic valve modes.
    (
        "valve",
        "relief_valve",
        "fails_to_open",
        "Fails to open at set pressure",
        "Protected volume at {tag} is not relieved",
        ["PT"],
        9,
        None,
        True,
    ),
    (
        "valve",
        "relief_valve",
        "fails_to_reseat",
        "Fails to reseat / leaks after lift",
        "{service} vents continuously through {tag}",
        ["PT", "TT"],
        6,
        None,
        True,
    ),
    (
        "valve",
        "relief_valve",
        "premature_lift",
        "Premature lift below set pressure",
        "{service} lost through {tag} during normal operation",
        ["PT"],
        5,
        None,
        True,
    ),
    (
        "valve",
        "relief_valve",
        "external_leak",
        "External leak at seat or body",
        "{service} released to the environment at {tag}",
        ["PT"],
        6,
        None,
        True,
    ),
    (
        "valve",
        "safety_valve",
        "fails_to_open",
        "Fails to open at set pressure",
        "Protected volume at {tag} is not relieved",
        ["PT"],
        9,
        None,
        True,
    ),
    (
        "valve",
        "safety_valve",
        "fails_to_reseat",
        "Fails to reseat / leaks after lift",
        "{service} vents continuously through {tag}",
        ["PT", "TT"],
        6,
        None,
        True,
    ),
    (
        "valve",
        "safety_valve",
        "premature_lift",
        "Premature lift below set pressure",
        "{service} lost through {tag} during normal operation",
        ["PT"],
        5,
        None,
        True,
    ),
    (
        "valve",
        "rupture_disc",
        "fails_to_burst",
        "Fails to burst at rated pressure",
        "Protected volume at {tag} is not relieved",
        ["PT"],
        9,
        None,
        True,
    ),
    (
        "valve",
        "rupture_disc",
        "premature_burst",
        "Premature burst / fatigue",
        "{service} lost through {tag}; system depressurises",
        ["PT"],
        6,
        None,
        True,
    ),
    # Actuated valves add actuator modes to the generic set.
    (
        "valve",
        "solenoid_valve",
        "coil_failure",
        "Coil open circuit / burn-out",
        "{tag} moves to its fail-safe position",
        ["ZS"],
        6,
        None,
        False,
    ),
    (
        "valve",
        "pneumatic_valve",
        "loss_of_supply",
        "Loss of actuator supply pressure",
        "{tag} moves to its fail-safe position",
        ["ZS", "PT"],
        6,
        None,
        False,
    ),
    (
        "valve",
        "motor_valve",
        "motor_stall",
        "Motor stall / gearbox failure",
        "{tag} stops mid-travel",
        ["ZS"],
        6,
        None,
        False,
    ),
    # Regulators.
    (
        "regulator",
        None,
        "fails_open",
        "Fails open (seat failure, creep, lock-up loss)",
        "Full upstream pressure passes {tag} to the downstream section",
        ["PT"],
        9,
        None,
        False,
    ),
    (
        "regulator",
        None,
        "fails_closed",
        "Fails closed",
        "No {service} supply downstream of {tag}",
        ["PT", "FT"],
        6,
        None,
        False,
    ),
    (
        "regulator",
        None,
        "droop",
        "Excessive droop / slow response",
        "Downstream pressure at {tag} falls below setpoint under flow",
        ["PT"],
        4,
        None,
        False,
    ),
    (
        "regulator",
        None,
        "external_leak",
        "External leak (bonnet, body)",
        "{service} released to the environment at {tag}",
        ["PT"],
        6,
        None,
        False,
    ),
    (
        "regulator",
        None,
        "hunting",
        "Hunting / instability",
        "Downstream pressure at {tag} oscillates",
        ["PT"],
        4,
        None,
        False,
    ),
    # Inline items (filters, hoses, meters, orifices, disconnects).
    (
        "inline",
        None,
        "external_leak",
        "External leak at joint or body",
        "{service} released to the environment at {tag}",
        ["PT"],
        7,
        None,
        False,
    ),
    (
        "inline",
        None,
        "blockage",
        "Blockage / restriction",
        "Reduced or no {service} flow through {tag}",
        ["PDT", "FT", "PT"],
        5,
        None,
        False,
    ),
    (
        "inline",
        "filter",
        "clogged",
        "Element clogged (high differential pressure)",
        "Reduced {service} flow through {tag}",
        ["PDT", "FT"],
        5,
        None,
        True,
    ),
    (
        "inline",
        "filter",
        "element_rupture",
        "Element rupture (particle release)",
        "Particulate carried downstream of {tag}",
        ["PDT"],
        7,
        None,
        True,
    ),
    (
        "inline",
        "filter",
        "external_leak",
        "External leak at housing",
        "{service} released to the environment at {tag}",
        ["PT"],
        6,
        None,
        True,
    ),
    (
        "inline",
        "coalescing_filter",
        "clogged",
        "Element clogged",
        "Reduced {service} flow through {tag}",
        ["PDT", "FT"],
        5,
        None,
        True,
    ),
    (
        "inline",
        "coalescing_filter",
        "element_rupture",
        "Element rupture",
        "Contaminant carried downstream of {tag}",
        ["PDT"],
        7,
        None,
        True,
    ),
    (
        "inline",
        "strainer",
        "clogged",
        "Screen clogged",
        "Reduced {service} flow through {tag}",
        ["PDT", "FT"],
        5,
        None,
        True,
    ),
    (
        "inline",
        "strainer",
        "screen_rupture",
        "Screen rupture",
        "Debris carried downstream of {tag}",
        ["PDT"],
        6,
        None,
        True,
    ),
    (
        "inline",
        "flex_hose",
        "rupture",
        "Hose rupture / burst",
        "{service} released at {tag}; line pressure lost",
        ["PT", "FT"],
        9,
        None,
        True,
    ),
    (
        "inline",
        "flex_hose",
        "external_leak",
        "Leak at end fitting or braid",
        "{service} released to the environment at {tag}",
        ["PT"],
        7,
        None,
        True,
    ),
    (
        "inline",
        "flex_hose",
        "kink",
        "Kink / collapse",
        "Reduced {service} flow through {tag}",
        ["FT", "PDT"],
        5,
        None,
        True,
    ),
    (
        "inline",
        "vacuum_jacketed_hose",
        "rupture",
        "Inner line rupture into jacket",
        "{service} released into the vacuum jacket at {tag}",
        ["PT", "TT"],
        9,
        None,
        True,
    ),
    (
        "inline",
        "vacuum_jacketed_hose",
        "loss_of_vacuum",
        "Loss of jacket vacuum",
        "Heat leak into {service} at {tag}; boil-off and frost",
        ["TT"],
        4,
        None,
        True,
    ),
    (
        "inline",
        "vacuum_jacketed_hose",
        "external_leak",
        "Leak at end fitting",
        "{service} released to the environment at {tag}",
        ["PT"],
        7,
        None,
        True,
    ),
    (
        "inline",
        "quick_disconnect",
        "fails_to_disconnect",
        "Fails to disconnect on command",
        "{tag} stays mated at separation",
        ["ZS"],
        9,
        None,
        True,
    ),
    (
        "inline",
        "quick_disconnect",
        "premature_disconnect",
        "Premature disconnect",
        "{service} released at {tag} while mated",
        ["ZS", "PT"],
        9,
        None,
        True,
    ),
    (
        "inline",
        "quick_disconnect",
        "external_leak",
        "Leak at interface seal",
        "{service} released to the environment at {tag}",
        ["PT"],
        7,
        None,
        True,
    ),
    (
        "inline",
        "quick_disconnect",
        "poppet_stuck",
        "Poppet stuck open after disconnect",
        "{service} released from the open half of {tag}",
        ["PT"],
        8,
        None,
        True,
    ),
    (
        "inline",
        "flow_meter",
        "erroneous_reading",
        "Erroneous reading",
        "{tag} reports a wrong {service} flow",
        ["FT", "PT"],
        6,
        None,
        True,
    ),
    (
        "inline",
        "flow_meter",
        "blockage",
        "Blockage / restriction",
        "Reduced {service} flow through {tag}",
        ["PDT", "PT"],
        5,
        None,
        True,
    ),
    (
        "inline",
        "flow_meter",
        "external_leak",
        "External leak at body or fitting",
        "{service} released to the environment at {tag}",
        ["PT"],
        6,
        None,
        True,
    ),
    (
        "inline",
        "turbine_meter",
        "erroneous_reading",
        "Erroneous reading / bearing failure",
        "{tag} reports a wrong {service} flow",
        ["FT", "PT"],
        6,
        None,
        True,
    ),
    (
        "inline",
        "orifice",
        "erosion",
        "Bore erosion / wrong size",
        "{tag} passes more {service} than designed",
        ["FT", "PT"],
        5,
        None,
        True,
    ),
    (
        "inline",
        "orifice",
        "blockage",
        "Blockage",
        "Reduced {service} flow through {tag}",
        ["PDT", "FT"],
        5,
        None,
        True,
    ),
    (
        "inline",
        "restriction_orifice",
        "erosion",
        "Bore erosion / wrong size",
        "{tag} passes more {service} than designed",
        ["FT", "PT"],
        5,
        None,
        True,
    ),
    (
        "inline",
        "restriction_orifice",
        "blockage",
        "Blockage",
        "Reduced {service} flow through {tag}",
        ["PDT", "FT"],
        5,
        None,
        True,
    ),
    (
        "inline",
        "field_weld",
        "leak",
        "Weld leak / crack",
        "{service} released to the environment at {tag}",
        ["PT"],
        8,
        None,
        True,
    ),
    (
        "inline",
        "shop_weld",
        "leak",
        "Weld leak / crack",
        "{service} released to the environment at {tag}",
        ["PT"],
        8,
        None,
        True,
    ),
    (
        "inline",
        "flange",
        "leak",
        "Gasket leak",
        "{service} released to the environment at {tag}",
        ["PT"],
        7,
        None,
        True,
    ),
    (
        "inline",
        "union",
        "leak",
        "Joint leak",
        "{service} released to the environment at {tag}",
        ["PT"],
        7,
        None,
        True,
    ),
    # Instruments.
    (
        "instrument",
        None,
        "erroneous_high",
        "Reads high",
        "{tag} reports a value above the true {service} state",
        ["PT"],
        7,
        None,
        False,
    ),
    (
        "instrument",
        None,
        "erroneous_low",
        "Reads low",
        "{tag} reports a value below the true {service} state",
        ["PT"],
        7,
        None,
        False,
    ),
    (
        "instrument",
        None,
        "drift",
        "Drift / slow response",
        "{tag} lags or drifts from the true value",
        [],
        5,
        None,
        False,
    ),
    (
        "instrument",
        None,
        "loss_of_signal",
        "Loss of signal / power",
        "No reading from {tag}",
        [],
        6,
        None,
        False,
    ),
    (
        "instrument",
        None,
        "process_leak",
        "Process connection leak",
        "{service} released to the environment at {tag}",
        ["PT"],
        6,
        None,
        False,
    ),
    # Equipment (tanks, pumps, vessels).
    (
        "equipment",
        None,
        "external_leak",
        "External leak / rupture",
        "{service} released from {name}",
        ["PT", "LT"],
        9,
        None,
        False,
    ),
    (
        "equipment",
        None,
        "loss_of_function",
        "Loss of function",
        "{name} stops performing its function",
        ["PT", "FT"],
        7,
        None,
        False,
    ),
    (
        "equipment",
        "pump",
        "fails_to_start",
        "Fails to start",
        "No {service} transfer from {name}",
        ["FT", "PT"],
        6,
        None,
        True,
    ),
    (
        "equipment",
        "pump",
        "trip",
        "Spurious trip during transfer",
        "{service} transfer stops; backflow through {name} possible",
        ["FT", "PT"],
        7,
        None,
        True,
    ),
    (
        "equipment",
        "pump",
        "seal_leak",
        "Seal leak",
        "{service} released at {name}",
        ["PT"],
        7,
        None,
        True,
    ),
    (
        "equipment",
        "pump",
        "cavitation",
        "Cavitation / loss of prime",
        "Reduced {service} flow; damage to {name}",
        ["FT", "PT"],
        5,
        None,
        True,
    ),
    (
        "equipment",
        "pump",
        "overspeed",
        "Overspeed / reverse rotation",
        "{name} damaged; {service} flow reversed",
        ["FT"],
        7,
        None,
        True,
    ),
    # Connectors are drawing devices, not hardware: no modes.
]


def ensure_default_failure_modes(db: Session) -> int:
    """Seed the library when it is empty. Returns the number inserted."""
    if db.scalar(select(FailureMode.id).limit(1)) is not None:
        return 0
    count = 0
    for (
        category,
        symbol_key,
        name,
        title,
        effect,
        hint,
        severity,
        modes,
        replaces,
    ) in DEFAULT_FAILURE_MODES:
        db.add(
            FailureMode(
                category=category,
                symbol_key=symbol_key,
                name=name,
                title=title,
                default_local_effect=effect,
                default_detection_hint=hint,
                default_severity=severity,
                applicable_modes=modes,
                replaces_category=replaces,
            )
        )
        count += 1
    db.flush()
    return count


def library(db: Session) -> list[FailureMode]:
    ensure_default_failure_modes(db)
    return list(
        db.scalars(
            select(FailureMode).order_by(
                FailureMode.category, FailureMode.symbol_key, FailureMode.name
            )
        )
    )


def modes_for(
    entries: list[FailureMode], category: str | None, symbol_key: str | None
) -> list[FailureMode]:
    """Active modes for an item: symbol-level entries, plus the category's unless
    a symbol-level entry replaces them."""
    if not category:
        return []
    symbol_entries = [
        entry
        for entry in entries
        if entry.active and entry.category == category and entry.symbol_key == symbol_key
    ]
    if any(entry.replaces_category for entry in symbol_entries):
        return symbol_entries
    category_entries = [
        entry
        for entry in entries
        if entry.active and entry.category == category and entry.symbol_key is None
    ]
    return category_entries + symbol_entries


def render_effect(template: str, *, tag: str | None, name: str | None, service: str | None) -> str:
    return (
        (template or "")
        .replace("{tag}", tag or name or "the item")
        .replace("{name}", name or tag or "the item")
        .replace("{service}", service or "process fluid")
    )
